notifications:
  email: false
os: linux
jobs:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64 PLAT=manylinux2010_x86_64
install:
- docker pull $DOCKER_IMAGE
script:
- docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
- ls wheelhouse/

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Dzq1P8BzlVzInHD3j0vNLmxYRDyz6OWc1m6KE21HTnAtSwV4prjo6DpJk4pg8yKSD8TSIBbbGdKnKG2VzUrs9tp6FQtSXATSPlRt5za94h9+FQNjLGxJM7quKVKEN5Kbip+8zJggp76DUmY1BKuaVZxHWmUAz4CtPRQcGQwoF2Fz4el21Vie2TOjwjZh7AdcPqY4H+yIDdQt7JqV7qF1LrT2vyuKQMMdgOnMDqBUZL1n3ORknClEuN69dqyyY3S69jtdL+3S5MP25hBnJznRlQSWYfDq4imV2oO6TPp2DSCSMrujUfLNiWaGBJsAPphGSp4bMVjwnRwiLvyLVfPUYaspPDl+iBdsn43kZ1GE03CISI3GYBazhFGVfnjUMvLSFuA1gpsCLBYJDDndpzODwOHoT7Hyuw2eEMYMK4IPXTJ27MUgemrYd/StGB7kEm3tgtpq9weyrJO3yU2rgJHr5xwdKjb4/+KiwcvUs+LUrH6g5obAQ/yJtpKsi0RdSQwZ3+OsIWklsmC6Afiswu8XnQ82dVd2IQw95hrzt71b7I9mTphhgc7/U28Ws4CKtozIC9r0dCQARMzvmhN7EFym9uPHnRE8nTR1ol/C1iTxuLtOMLOps75Qxg0EROiwvbySoJbBHCxrTPtoldn1Qne97mDn0joAd2yD05rhigHOfRA=
  file: wheelhouse/wildboar*.whl
  file_glob: true
  on:
    tags: true
    repo: isaksamsten/wildboar
